"""drop the legacy engagement org_name column

Revision ID: 0014
Revises: 0013
Create Date: 2026-06-24

The free-text ``engagements.org_name`` column predates both multi-tenancy
(``org_id``) and the real ``clients`` entity (``client_id``) introduced in
``0013``. The customer-company role it once served is now owned by the
``clients`` row each engagement points at, so the column is redundant on
every read/write path. Drop it.

``downgrade()`` re-adds the column as nullable text. The original values
are NOT recoverable this way — restore the pre-migration DB snapshot if
they are needed.

Hand-written (not autogenerated): `alembic revision --autogenerate`
mis-reports the raw-SQL schema as drift (TEXT vs AutoString, RLS column
grants it can't see), so every schema change here goes through
`op.execute()` like the rest of this migration tree.
"""
from alembic import op

revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("alter table public.engagements drop column org_name;")


def downgrade() -> None:
    op.execute("alter table public.engagements add column org_name text;")
